<section id="float-line">
	<div class="header">    
		<h2>Label</h2><h1>Studio</h1><a href="index.php" style="text-decoration: none; color: white;"><h3><strong>></strong>home</h3></a>
	</div>
	<h1 class="artiste">Le son de la semaine</h1>

	<div class="img-lecteur">
		<div class="bg-text-animate">
			<marquee class="opacity-texte" behavior="scroll" direction="right" width="100%">
				<img src="img/texte-anime.svg">
			</marquee>
			<marquee class="opacity-texte-2" behavior="loop">
				<img src="img/texte-anime.svg">
			</marquee>
		</div>
		<div class='music-card playing'>
			<div class='image'></div>
			<div class='wave'></div>
			<div class='wave'></div>
			<div class='wave'></div>
			<div class='info'>
				<p class='title'>Cashmere Tears</p> 
				<p class='artist'>Kojey Radical</p>
				<img class="fa fa-play trigger" src="img/play.svg" aria-hidden="true">
				<img class="fa fa-pause trigger" src="img/pause.svg" aria-hidden="true">
			</div>   
		</div>
	</div>
</section>	
<section id="white-section">
	<h2 class="artiste">Nos artistes partenaires</h2>
	<div id="page-wrap">
		<section class="image-gallery group">
			<figure tabindex="1">
				<img src="img/artistes/adrien.jpeg" alt="jump, matey">
				<figcaption>Adrien Wagner</figcaption>
			</figure>
			<figure tabindex="2">
				<img src="img/artistes/dpr.png" alt="jump, matey">
				<figcaption>DPR LIVE</figcaption>
			</figure>
			<figure tabindex="3">
				<img src="img/artistes/dua-lipa.png" alt="jump, matey">
				<figcaption>Dua Lipa</figcaption>
			</figure>
			<figure tabindex="4">
				<img src="img/artistes/eddy-de-pretto.png" alt="jump, matey">
				<figcaption>Eddy De Pretto</figcaption>
			</figure>
			<figure tabindex="5">
				<img src="img/artistes/gambino.png" alt="jump, matey">
				<figcaption>Gambino</figcaption>
			</figure>
			<figure tabindex="6">
				<img src="img/artistes/kojay.png" alt="jump, matey">
				<figcaption>Kojey Radical</figcaption>
			</figure>
			<figure tabindex="7">
				<img src="img/artistes/lil-nas.png" alt="jump, matey">
				<figcaption>Lil Nas X</figcaption>
			</figure>
			<figure tabindex="8">
				<img src="img/artistes/lila.png" alt="jump, matey">
				<figcaption>Canine + Isla</figcaption>
			</figure>
			<figure tabindex="9">
				<img src="img/artistes/mahilia.png" alt="jump, matey">
				<figcaption>Mahalia</figcaption>
			</figure>
			<figure tabindex="10">
				<img src="img/artistes/mayra-andrade.png" alt="jump, matey">
				<figcaption>Mayra Andrade</figcaption>
			</figure>
			<figure tabindex="11">
				<img src="img/artistes/the-beatles.png" alt="jump, matey">
				<figcaption>The Beatles</figcaption>
			</figure>
			<figure tabindex="12">
				<img src="img/artistes/the-internet.png" alt="jump, matey">
				<figcaption>The Internet</figcaption>
			</figure>
		</section>
	</div>
</section>
<section class="lecteur-v2">
	<h2 class="artiste">Les sons du mois</h2>
	<div class="player">
		<audio controls="controls">
		</audio>
		<div class="player"></div>
		<div class="p-bg">
			<div class="p-list" onclick="pickSong(0)">
				<figure>
					<img src="img/artistes-v2/mayra-andrade.png" alt="jump, matey">
					<figcaption>Mayra Andrade</figcaption>
				</figure>Manga
			</div>
			<div class="p-list" onclick="pickSong(1)">
				<figure>
					<img src="img/artistes-v2/mahalia.png" alt="jump, matey">
					<figcaption>Mahalia</figcaption>
				</figure>Sober
			</div>
			<div class="p-list" onclick="pickSong(2)">
				<figure>
					<img src="img/artistes-v2/lil-nas-x.png" alt="jump, matey">
					<figcaption>Lil Nas X</figcaption>
				</figure>Montero
			</div>
		</div>
	</div>
</section>