<section class="contact-bold">
    <div class="header">    
		<h2>Nous</h2><h1>Contactez</h1><a href="index.php" style="text-decoration: none; color: white;"><h3><strong>></strong>home</h3></a>
	</div>
    <article>
            <p>Pace Production</p>
            <p>Campus de Ker Lann, Rue Pierre de Maupertuis</p>
            <p>35170 Bruz</p>
            <p>Téléphone : 02 57 24 04 15</p>
    </article>
</section>
<section>
    <form action="contact.php" method="POST">
        <fieldset>
            <legend>Contactez-nous</legend>
            
            <input type="text" name="Prenom" placeholder="Votre prénom">
            <input type="text" name="Nom" placeholder="Votre nom">
            <input type="email" name="Email" placeholder="Votre email">
    
            <textarea name="Contenu" rows="1" placeholder="Votre message"></textarea>
        
            <button class="contact-button" type="submit" name="button">Envoyer</button>
            <button class="contact-button" type="reset" name="button">Effacer</button>
        </fieldset>
    </form>
</section>


<article>
    <small>
        <p class="mentions">&copy; Pace Production | Tous droits réservés | <a href="mentionsLegales.php">Mentions légales</a></p>
        <p>Le contenu du présent site web doit être utilisé à des fins informatives et non-commerciales</p>
    </small>
</article>  