<section class="main">
<div class="header">
<h2>Notre</h2><h1>Label</h1><a href="index.php" style="text-decoration: none; color: white;"><h3><strong>></strong>home</h3></a>
    </div>
    <div id="dynamicContent"></div>
    </main>
    <div class="logo-pace">
        <img src="img/logo/logo.svg">
        <svg class="pulse" viewBox="0 0 1024 1024">
            <circle id="Oval" cx="512" cy="512" r="512"></circle>
            <circle id="Oval" cx="512" cy="512" r="512"></circle>
            <circle id="Oval" cx="512" cy="512" r="512"></circle>
        </svg>
    </div>
    <button class="ham">
        <span class="menuIcon material-icons">
            <div class="before-hover">
                <div><img id="trigger" src="img/down-arrow.png" alt=""></div>
            </div>
        </span>
        <span class="xIcon material-icons">
            <div class="before-hover">
                <div><img id="trigger-1" src="img/up-arrow.png" alt=""></div>
            </div>
        </span>
    </button>
    <div class="menu">
        <p>
            Pace production est née de quatre cerveaux aimant la musique plus que tout.
            Cette collaboration amicale donne vie aux divers projets musicaux des artistes qui veulent s’exprimer.
            Nous les accompagnons sur les différents aspects du métier, leur proposons des services adaptés et personnalisés.
            Nous voulons avant tout créer du liens avec nos artistes.
            C’est avec notre esprit multiculturel, générationnel, frais et dynamique que nous soutenons les visions et paroles des artistes professionnels à en devenir.
            Les aider dans la fabrication, l’édition, la production et la commercialisation de leurs œuvres musicales reste au cœur de nos aspirations.
        </p>
    </div>
</section>