<section>
    <div class="header">    
		<h2>Nos</h2><h1>Partenaires</h1><a href="index.php" style="text-decoration: none; color: white;"><h3><strong>></strong>home</h3></a>
	</div>
	<div id="page-wrap">
<section class="image-gallery group">
    <figure tabindex="1">
    <a href="https://fr-fr.facebook.com" target="_blank"><i class="fab fa-facebook-f"></i></a>
        <figcaption>Facebook</figcaption>
    </figure>
    <figure tabindex="2">
    <a href="https://www.instagram.com/?hl=fr" target="_blank"><i class="fab fa-instagram"></i></a>
        <figcaption>Instagram</figcaption>
    </figure>
    <figure tabindex="3">
    <a href="https://www.spotify.com/fr/" target="_blank"><i class="fab fa-spotify"></i></a>
        <figcaption>Spotify</figcaption>
    </figure>
    <figure tabindex="1">
    <a href="https://www.deezer.com/fr/" target="_blank"><i class="fab fa-deezer"></i></a>
        <figcaption>Deezer</figcaption>
    </figure>
    <figure tabindex="1">
    <a href="https://www.apple.com/fr/apple-music/" target="_blank"><i class="fab fa-apple"></i></a>
        <figcaption>Apple Music</figcaption>
    </figure>
    <figure tabindex="1">
    <a href="https://www.youtube.com/" target="_blank"><i class="fab fa-youtube"></i></a>
        <figcaption>You Tube</figcaption>
    </figure>
    <figure tabindex="1">
    <a href="https://music.amazon.fr/" target="_blank"><i class="fab fa-amazon"></i></a>
        <figcaption>Amazon Music</figcaption>
    </figure>
    <figure tabindex="1">
    <a href="https://www.npr.org/music" target="_blank"><img src="img/npr.jpeg"></a>
        <figcaption>NPR Music</figcaption>
    </figure>
</section>